# This is a basic workflow to help you get started with Actions

name: Package Java User Project

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "package"
  package:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: openhack3mg4iju8acr.azurecr.io
          repository: team-3/user-java
          tags: latest,${{ github.sha }}
          dockerfile: apis/user-java/Dockerfile
          path: apis/user-java

      - name: Deploy User-Java Project
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'openhack3mg4iju8userjava'
          publish-profile: ${{ secrets.OH_PUBLISH_PROFILE }}
          images: 'openhack3mg4iju8acr.azurecr.io/team-3/user-java:${{ github.sha }}'
          slot-name: staging
